### PR TITLE
Fix typos in focus editor group commands (#81)

### PR DESCRIPTION
**Pull request by CAESIUS-TIM**
fix https://github.com/VSpaceCode/vscode-which-key/issues/81

### CODE REVIEW

**Comment by MarcoIeni** [comment]
I would remove the word "group" because we call them just "editor" I think.

Also, what's the difference between `previous` and `left` in this context?

**Comment by CAESIUS-TIM** [comment]
`previous` also focus left but in a cycle, meaning it will focus the rightmost window when you're on the leftmost.

**Comment by MarcoIeni** [comment]
> meaning it will focus the rightmost window when you're on the leftmost

This seems like a "feature" to me 😅 but let's wait on @stevenguh to see if he has any preference. 👍

**Comment by stevenguh** [comment]
These makes sense to me in a first glance. which-key uses the the vscode naming

**Review by MarcoIeni — APPROVED** [review]
ok, merging than, thanks!

**Pull request merged**
